services:
  swagger-editor:
    container_name: swagger-editor
    image: swaggerapi/swagger-editor
    ports:
      - "8081:8080"
    volumes:
      - ./swagger:/swagger
    environment:
      SWAGGER_FILE: /swagger/openapi.yaml

  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui
    ports:
      - "8082:8080"
    volumes:
      - ./swagger:/swagger
    environment:
      SWAGGER_JSON: /swagger/openapi.yaml

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d:ro
      - ./db/data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_DEFAULT_EMAIL: "admin@mail.ru"    # без этих строк
      PGADMIN_DEFAULT_PASSWORD: "admin"         # контейнер не запускается
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "8083:80"
    restart: unless-stopped
    depends_on:
      - postgres

  my-meteo:
    container_name: my-meteo
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYMETEO_DB_SERVER_ADDRESS: "postgres"
    ports:
      - "9000:9000"
    restart: no
    depends_on:
      - postgres

volumes:
  pgadmin-data: