services:
  swagger-editor:
    container_name: swagger-editor
    image: swaggerapi/swagger-editor
    ports:
      - "8081:8080"
    volumes:
      - ./swagger:/swagger
    environment:
      SWAGGER_FILE: /swagger/openapi.yaml

  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui
    ports:
      - "8082:8080"
    volumes:
      - ./swagger:/swagger
    environment:
      SWAGGER_JSON: /swagger/openapi.yaml