openapi: 3.0.0
info:
  title: MyMeteo
  description: service for receiving data from the sensor on the OpenAPI 3.0 specification.
  version: 1.0.0
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

paths:
  /users/register:
    post:
      summary: Регистрация нового пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Успешная регистрация пользователя
          content:
            application/json:
              schema:
                type: string
                example: "User registered successfully."
        '400':
          description: Ошибка при регистрации пользователя
          content:
            application/json:
              schema:
                type: string
                example: "Username is already taken."

  /sensors:
    post:
      summary: Регистрация нового сенсора
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sensor'
      responses:
        '201':
          description: Успешная регистрация сенсора
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SensorRegistrationResponse'

    get:
      summary: Получение всех измерений
      responses:
        '200':
          description: Список всех измерений
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MeasurementResponse'

  /measurements/rainyDaysCount:
    get:
      summary: Подсчет количества дождливых дней
      responses:
        '200':
          description: Количество дождливых дней
          content:
            application/json:
              schema:
                type: integer
                format: int32
                description: "Количество дней с осадками"

  /measurements:
    post:
      summary: Добавление нового измерения
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Measurement'
      responses:
        '201':
          description: Успешное добавление измерения
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeasurementResponse'
components:
  schemas:
    Sensor:
      type: object
      properties:
        name:
          type: string
          description: "Имя сенсора"
      required:
        - name

    SensorRegistrationResponse:
      type: object
      properties:
        id:
          type: integer
          description: "Идентификатор сенсора"
        name:
          type: string
          description: "Имя сенсора"

    MeasurementResponse:
      type: object
      properties:
        id:
          type: integer
          description: "Идентификатор измерения"
        value:
          type: number
          format: float
          description: "Значение температуры"
        raining:
          type: boolean
          description: "Флаг, указывающий на наличие осадков"
        sensor:
          $ref: '#/components/schemas/Sensor'

    Measurement:
      type: object
      properties:
        value:
          type: number
          format: float
          description: "Значение температуры"
        raining:
          type: boolean
          description: "Флаг, указывающий на наличие осадков"
        sensor:
          $ref: '#/components/schemas/Sensor'
      required:
        - value
        - raining
        - sensor
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
          description: "Идентификатор пользователя"
        username:
          type: string
          description: "Имя пользователя"
          example: "admin"
        email:
          type: string
          description: "Электронная почта пользователя"
          example: "user@example.com"